### PR TITLE
gettingstarted: use pipenv instead of pip

### PR DESCRIPTION
**Pull request by ppanero**
Fix Documentation to use pipenv instead of pip.

Related to https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/83

### CODE REVIEW

**Comment by egabancho** [comment]
I think we would also need to update this line as well `cookiecutter gh:inveniosoftware/cookiecutter-invenio-instance -c v3.0` to point to the new version (once it's done) otherwise `pipenv` is not supported.

**Comment by ppanero** [comment]
@egabancho True! Fixed, thanks! :)

**Comment by lnielsen** [comment]
This branch is ready for merge, but cannot be merged until the very last moment we have everything released.

**Comment by ppanero** [comment]
Closing this PR in favour of https://github.com/inveniosoftware/inveniosoftware.org/pull/99 which documents the merge of cookiecutter instance and datamodel

**Pull request closed without merging**
