### PR TITLE
sites: updated join2 texts

### PR DESCRIPTION
**Pull request by aw-bib**
* Updates texts for Museum Zitadelle Jülich, a join2 (http://join2.de)
  repositories to the official version. Add project reference, URL,
  screenshot (addresses join2/join2-data#1437)

   Signed-off-by: Alexander Wagner <alexander.wagner@desy.de>))

### CODE REVIEW

**Comment by jbenito3** [comment]
@aw-bib Would you mind if I change a bit the screenshot? In my test machine it displays a bit blurred. :/
I could push a new version to your repo and if you give me the green light I could integrate it right ahead.

**Comment by aw-bib** [comment]
Feel free. I wonder what went wrong tough. Any idea?

**Comment by jbenito3** [comment]
I think it was only an optical effect due to the amount of white bg and black text...I have done a screenshot with the search results to give it a bit of colour. It feels a bit better to my eyes, WDYT?

**Comment by aw-bib** [comment]
Fine with me. :) I thought you always want the "first page", that's why I chose it.

**Pull request merged**
