### PR TITLE
blog post v12

### PR DESCRIPTION
**Pull request by fenekku**
- **new blog post invenio-rdm-v12.0**
- **fix blog post title**
- **blog-post v12: edit for publication [+]**

### CODE REVIEW

**Comment by fenekku** [comment]
Sorry about creating another PR for this! Since the original PR was from @mfenner's master branch I couldn't push to it and it was going to be simpler if I just submitted the sprinkling of changes I had.

I have snuck in a fix for the blog post section titles that have bothered me for a while:

**before**

image

**after**

image

(and on the /blog/ URL too)

**Review by mfenner — APPROVED** [review]
LGTM

**Comment by mfenner** [comment]
Good to see three authors.

**Review by saragon02 — APPROVED** [review]
Thank you both! All the updates look great to me. I'll merge this PR.

**Pull request merged**
